 P=rands(2,500);
 plot(P(1,:),P(2,:),'rp');
 axis([-1 1 -1 1]);
 xlabel('P1');
 ylabel('P1');
 net=newsom([0 1;0 1],[5 6]);
 cla;
 plotsom(net.IW{1,1},net.layers{1}.distances);
 axis([0 1 0 1]);
 xlabel('w(i1)');
 ylabel('w(i2)');
 net.trainParam.epochs=1;
 net=train(net,P);
 cla
 plotsom(net.iw{1,1},net.layers{1}.distances);
 axis([-1 1 -1 1]);
 xlabel('w(i1)');
 ylabel('w(i2)');
 p=[0.5,0.3];
 a=sim(net,p);